### ISSUE TITLE
Silverstripe v4

### ISSUE THREAD

**Issue by gfeller** [bummzack/page-blocks#19]
Are there any plans to make this plugin Silverstripe v4 compatible?

**Comment by bummzack** [comment]
No, there are no plans for an SS4 release. If you need content-blocks with SS4, I suggest you use elemental (https://github.com/dnadesign/silverstripe-elemental).

Of course you can upgrade this module to SS4 if you want, but one of the goals of the elemental-module was to reduce the fragmentation of many competing content-block modules in favor of an officially supported one.
